### ISSUE TITLE
Full system simulation example "Class Cache has no parameter hit_latency"

### ISSUE THREAD

**Issue by DIV-submission** [powerjg/learning_gem5#2]
Hello,

I would like to try the full system simulation example, so I downloaded scripts in this category, and try to run it in `gem5`.

However, I got the following error:

    ☁  gem5  ./build/X86/gem5.opt configs/cacheD/run.py
    gem5 Simulator System.  http://gem5.org
    gem5 is copyrighted software; use the --copyright option for details.

    gem5 compiled Dec 20 2016 20:11:15
    gem5 started Dec 21 2016 13:22:58
    gem5 executing on lrs-dwu01, pid 27677
    command line: ./build/X86/gem5.opt configs/cacheD/run.py

    Traceback (most recent call last):
     File "<string>", line 1, in <module>
      File "/home/work/gem5/src/python/m5/main.py", line 400, in main
        exec filecode in scope
      File "configs/test/run.py", line 49, in <module>
        system = MySystem(opts)
      File "configs/test/system.py", line 68, in __init__
        x86.init_fs(self, self.membus)
      File "configs/test/x86.py", line 85, in init_fs
        addr_ranges = system.mem_ranges)
      File "/home/work/gem5/src/python/m5/SimObject.py", line 1046, in __init__
    setattr(self, key, val)
      File "/home/work/gem5/src/python/m5/SimObject.py", line 1150, in __setattr__
    % (self.__class__.__name__, attr)
AttributeError: Class Cache has no parameter hit_latency

Am I doing anything wrong here?

**Comment by powerjg** [comment]
A recent gem5 change updated the caches to have a separate tag_latency and data_latency. You can replace "hit_latency" with tag/data_latency in caches.py to fix this. I should be posting updated code very soon.

**Comment by DIV-submission** [comment]
@powerjg Thank you for your quick response! I am in rush for some experiments so sorry I cannot wait too long.. 

I actually posted a question on the `gem5` email list, asking how to simulate multithread x86 32-bit programs, as I am trapped to use m5threads library. It seems that right now the only thing I can do is to use the full system simulation, am I correct? 


Besides, I updated the `hit_latency` with `data_latency` in `caches.py` and `x86.py`, and then got new expecption:


   Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/szw175/work/gem5/src/python/m5/main.py", line 400, in main
    exec filecode in scope
    File "./run.py", line 48, in <module>
    system = MySystem(opts)
    File "./system.py", line 68, in __init__
    x86.init_fs(self, self.membus)
    File "./x86.py", line 85, in init_fs
    addr_ranges = system.mem_ranges)
    File "/home/szw175/work/gem5/src/python/m5/SimObject.py", line 1046, in __init__
    setattr(self, key, val)
    File "/home/szw175/work/gem5/src/python/m5/SimObject.py", line 1150, in __setattr__
    % (self.__class__.__name__, attr)
  AttributeError: Class Cache has no parameter forward_snoops

Would you mind to take a look on that? Thank you!

**Comment by winterNan** [comment]
Can you please explain a bit on what the "filecode" (e.g. in main.py.cc) is? 

Thank you in advance!
